name: Strava Import & Build

on:
  workflow_dispatch: # Permet de lancer manuellement
  schedule:
    - cron: '0 3 * * *' # Tous les jours à 3h UTC

jobs:
  import-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl, pdo, pdo_sqlite, curl, dom, gd, zip, bcmath, ctype, fileinfo, openssl, phar, session, simplexml, tokenizer, xml, xmlreader, xmlwriter, pcntl, iconv


      - name: Remove vendor directory
        run: rm -rf vendor
        working-directory: ${{ github.workspace }}

      - name: Clear Composer cache
        run: composer clear-cache
        working-directory: ${{ github.workspace }}


      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader
        working-directory: ${{ github.workspace }}

      - name: Debug: search /var/www/bin/console in vendor
        run: grep -r '/var/www/bin/console' vendor/ || echo 'No match'
        working-directory: ${{ github.workspace }}



      - name: Debug: show DoctrineMigrationRunner.php
        run: cat src/Infrastructure/Doctrine/Migrations/DoctrineMigrationRunner.php
        working-directory: ${{ github.workspace }}

      - name: Debug: search /var/www/bin/console
        run: grep -r '/var/www/bin/console' . || echo 'No match'
        working-directory: ${{ github.workspace }}

      - name: Import Strava data
        run: php bin/console app:strava:import-data
        working-directory: ${{ github.workspace }}

      - name: Build HTML files
        run: php bin/console app:strava:build-files
        working-directory: ${{ github.workspace }}
